addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: e29664af-be96-4f41-be64-f40e2a805625
after_success:
- ./df-build.sh
before_install:
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
  $HOME/.m2/settings.xml
cache:
  directories:
  - $HOME/.m2
install: mvn install -DskipTests=true
jdk:
- oraclejdk8
language: java
script: mvn test
sudo: false
# Modified by Insights Service at 2016-06-29 13:22:41.476823
