addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: 0a6bc47b-571b-42e8-a6db-c0ea42b10406
after_success:
- ./df-build.sh
cache:
  directories:
  - $HOME/.m2
install: mvn install -DskipTests=true
jdk:
- oraclejdk8
language: java
script: mvn test
sudo: false
# Modified by Insights Service at 2016-06-06 11:55:14.581036
